#!/usr/bin/env bash

echo "Creating site dir"
mkdir site

echo "Moving to web directory"
cd web

echo "Mustache in settings"
MUSTACHE_VIEW="{\"API_BASE_URL\":\"${API_BASE_URL}\"}"
echo "${MUSTACHE_VIEW}" | npx mustache - ./src/index.template.html > ./src/index.html
echo "install deps"
npm ci

echo "Running web build"
npm run build

echo "List site contents"
ls ../site