/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { BlackCard, } from "./services/card-source-getter";
import { MatchResults, RouterHistory, } from "@stencil/router";
export namespace Components {
    interface AppHome {
    }
    interface AppRoot {
    }
    interface BlackCard {
        "card": BlackCard;
    }
    interface CardDirectoryPage {
    }
    interface GameLobbyPage {
        "history": RouterHistory;
        "match": MatchResults;
    }
    interface GamePage {
        "history": RouterHistory;
        "match": MatchResults;
    }
    interface MainGamePage {
        "history": RouterHistory;
        "match": MatchResults;
    }
    interface PlayerPage {
        "history": RouterHistory;
        "match": MatchResults;
    }
    interface WhiteCard {
        "selected": boolean;
        "text": string;
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLBlackCardElement extends Components.BlackCard, HTMLStencilElement {
    }
    var HTMLBlackCardElement: {
        prototype: HTMLBlackCardElement;
        new (): HTMLBlackCardElement;
    };
    interface HTMLCardDirectoryPageElement extends Components.CardDirectoryPage, HTMLStencilElement {
    }
    var HTMLCardDirectoryPageElement: {
        prototype: HTMLCardDirectoryPageElement;
        new (): HTMLCardDirectoryPageElement;
    };
    interface HTMLGameLobbyPageElement extends Components.GameLobbyPage, HTMLStencilElement {
    }
    var HTMLGameLobbyPageElement: {
        prototype: HTMLGameLobbyPageElement;
        new (): HTMLGameLobbyPageElement;
    };
    interface HTMLGamePageElement extends Components.GamePage, HTMLStencilElement {
    }
    var HTMLGamePageElement: {
        prototype: HTMLGamePageElement;
        new (): HTMLGamePageElement;
    };
    interface HTMLMainGamePageElement extends Components.MainGamePage, HTMLStencilElement {
    }
    var HTMLMainGamePageElement: {
        prototype: HTMLMainGamePageElement;
        new (): HTMLMainGamePageElement;
    };
    interface HTMLPlayerPageElement extends Components.PlayerPage, HTMLStencilElement {
    }
    var HTMLPlayerPageElement: {
        prototype: HTMLPlayerPageElement;
        new (): HTMLPlayerPageElement;
    };
    interface HTMLWhiteCardElement extends Components.WhiteCard, HTMLStencilElement {
    }
    var HTMLWhiteCardElement: {
        prototype: HTMLWhiteCardElement;
        new (): HTMLWhiteCardElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-root": HTMLAppRootElement;
        "black-card": HTMLBlackCardElement;
        "card-directory-page": HTMLCardDirectoryPageElement;
        "game-lobby-page": HTMLGameLobbyPageElement;
        "game-page": HTMLGamePageElement;
        "main-game-page": HTMLMainGamePageElement;
        "player-page": HTMLPlayerPageElement;
        "white-card": HTMLWhiteCardElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface AppRoot {
    }
    interface BlackCard {
        "card"?: BlackCard;
    }
    interface CardDirectoryPage {
    }
    interface GameLobbyPage {
        "history"?: RouterHistory;
        "match"?: MatchResults;
    }
    interface GamePage {
        "history"?: RouterHistory;
        "match"?: MatchResults;
    }
    interface MainGamePage {
        "history"?: RouterHistory;
        "match"?: MatchResults;
    }
    interface PlayerPage {
        "history"?: RouterHistory;
        "match"?: MatchResults;
    }
    interface WhiteCard {
        "selected"?: boolean;
        "text"?: string;
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-root": AppRoot;
        "black-card": BlackCard;
        "card-directory-page": CardDirectoryPage;
        "game-lobby-page": GameLobbyPage;
        "game-page": GamePage;
        "main-game-page": MainGamePage;
        "player-page": PlayerPage;
        "white-card": WhiteCard;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "black-card": LocalJSX.BlackCard & JSXBase.HTMLAttributes<HTMLBlackCardElement>;
            "card-directory-page": LocalJSX.CardDirectoryPage & JSXBase.HTMLAttributes<HTMLCardDirectoryPageElement>;
            "game-lobby-page": LocalJSX.GameLobbyPage & JSXBase.HTMLAttributes<HTMLGameLobbyPageElement>;
            "game-page": LocalJSX.GamePage & JSXBase.HTMLAttributes<HTMLGamePageElement>;
            "main-game-page": LocalJSX.MainGamePage & JSXBase.HTMLAttributes<HTMLMainGamePageElement>;
            "player-page": LocalJSX.PlayerPage & JSXBase.HTMLAttributes<HTMLPlayerPageElement>;
            "white-card": LocalJSX.WhiteCard & JSXBase.HTMLAttributes<HTMLWhiteCardElement>;
        }
    }
}
