/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MatchResults, } from "@stencil/router";
import { BlackCard, } from "./services/card-source-getter";
export namespace Components {
    interface AppHome {
    }
    interface AppProfile {
        "match": MatchResults;
    }
    interface AppRoot {
    }
    interface BlackCard {
        "card": BlackCard;
    }
    interface CardDirectoryPage {
    }
    interface GamePage {
        "match": MatchResults;
    }
    interface WhiteCard {
        "selected": boolean;
        "text": string;
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLBlackCardElement extends Components.BlackCard, HTMLStencilElement {
    }
    var HTMLBlackCardElement: {
        prototype: HTMLBlackCardElement;
        new (): HTMLBlackCardElement;
    };
    interface HTMLCardDirectoryPageElement extends Components.CardDirectoryPage, HTMLStencilElement {
    }
    var HTMLCardDirectoryPageElement: {
        prototype: HTMLCardDirectoryPageElement;
        new (): HTMLCardDirectoryPageElement;
    };
    interface HTMLGamePageElement extends Components.GamePage, HTMLStencilElement {
    }
    var HTMLGamePageElement: {
        prototype: HTMLGamePageElement;
        new (): HTMLGamePageElement;
    };
    interface HTMLWhiteCardElement extends Components.WhiteCard, HTMLStencilElement {
    }
    var HTMLWhiteCardElement: {
        prototype: HTMLWhiteCardElement;
        new (): HTMLWhiteCardElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
        "black-card": HTMLBlackCardElement;
        "card-directory-page": HTMLCardDirectoryPageElement;
        "game-page": HTMLGamePageElement;
        "white-card": HTMLWhiteCardElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface AppProfile {
        "match"?: MatchResults;
    }
    interface AppRoot {
    }
    interface BlackCard {
        "card"?: BlackCard;
    }
    interface CardDirectoryPage {
    }
    interface GamePage {
        "match"?: MatchResults;
    }
    interface WhiteCard {
        "selected"?: boolean;
        "text"?: string;
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-profile": AppProfile;
        "app-root": AppRoot;
        "black-card": BlackCard;
        "card-directory-page": CardDirectoryPage;
        "game-page": GamePage;
        "white-card": WhiteCard;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "black-card": LocalJSX.BlackCard & JSXBase.HTMLAttributes<HTMLBlackCardElement>;
            "card-directory-page": LocalJSX.CardDirectoryPage & JSXBase.HTMLAttributes<HTMLCardDirectoryPageElement>;
            "game-page": LocalJSX.GamePage & JSXBase.HTMLAttributes<HTMLGamePageElement>;
            "white-card": LocalJSX.WhiteCard & JSXBase.HTMLAttributes<HTMLWhiteCardElement>;
        }
    }
}
